import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
      backgroundColor: '#f5f5f5',
    },
    title: {
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 8,
      color: '#333',
    },
    subtitle: {
      fontSize: 14,
      color: '#666',
      marginBottom: 20,
    },
    profileHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
      padding: 16,
      backgroundColor: '#fff',
      borderRadius: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3.84,
      elevation: 5,
      width: '100%',
    },
    avatar: {
      width: 60,
      height: 60,
      borderRadius: 30,
      marginRight: 16,
    },
    avatarPlaceholder: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: '#007AFF',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 16,
    },
    avatarText: {
      color: '#fff',
      fontSize: 20,
      fontWeight: 'bold',
    },
    profileInfo: {
      flex: 1,
    },
    name: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#333',
      marginBottom: 4,
    },
    email: {
      fontSize: 14,
      color: '#666',
      marginBottom: 4,
    },
    bio: {
      fontSize: 12,
      color: '#888',
      fontStyle: 'italic',
    },
    paramContainer: {
      flexDirection: 'row',
      marginBottom: 8,
      backgroundColor: '#fff',
      padding: 12,
      borderRadius: 8,
      width: '100%',
    },
    paramLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: '#333',
      marginRight: 8,
    },
    paramValue: {
      fontSize: 14,
      color: '#666',
    },
    detailsContainer: {
      width: '100%',
      backgroundColor: '#fff',
      borderRadius: 12,
      padding: 16,
      marginBottom: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3.84,
      elevation: 5,
    },
    detailRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: '#f0f0f0',
    },
    detailLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: '#333',
    },
    detailValue: {
      fontSize: 14,
      color: '#666',
    },
    errorText: {
      color: '#ff4444',
      fontSize: 12,
      textAlign: 'center',
      marginTop: 8,
    },
    buttonContainer: {
      width: '100%',
    },
  }); 